name: A workflow for my Hello World file
on: 
  push:
  workflow_dispatch:

jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
      - name: 'default'
        run: echo Defaut
      - name: 'conditional'
        run: echo Conditional
        if: ${{ (github.event_name == 'workflow_dispatch') && (github.ref_name == 'main') }}
  say_hello:
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo Hello $NAME!
            echo -in $HOME
      env:
        NAME: ${{ github.ref_name }}
        HOME: ${{ github.event_name }}
  build:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
