name: A workflow for my Hello World file
on: 
  push:
  workflow_dispatch:

jobs:
  say_hello:
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo Hello $NAME!
            if: ${{ github.event_name == 'workflow_dispatch' }}
            echo -in $HOME
      env:
        NAME: ${{ github.event.type }}
        HOME: ${{ github.event_name }}
  build:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
